name: 'base'

on:
  push:
    paths:
      - 'run.sh'
      - '.github/workflows/base.yml'
      - 'build_*.dockerfile'
      - 'run_*.dockerfile'
      - 'ls_base.dockerfile'
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,16 * *'

jobs:

  base:
    strategy:
      fail-fast: false
      matrix:
        include: [
          { distro: arch,   version: ''       },
          { distro: debian, version: buster   },
          { distro: debian, version: bullseye },
          { distro: fedora, version: 35       },
          { distro: fedora, version: 36       },
          { distro: ubuntu, version: 20       },
          { distro: ubuntu, version: 22       },
          { distro: ls,     version: ''       },
        ]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - run: ./run.sh -c $DISTRIBUTION $VERSION
      env:
        DISTRIBUTION: ${{ matrix.distro }}
        VERSION:      ${{ matrix.version }}

    - name: 'Build ghdl/debug:base'
      if: (matrix.distro == 'debian') && (matrix.version == 'buster')
      run: |
        docker build -t ghdl/debug:base - <<-EOF
        FROM ghdl/build:buster-mcode
        RUN apt update -qq && apt install -y python3-pip gnat-gps graphviz gdb \
         && ln -s /usr/bin/pip3 /usr/bin/pip
        EOF

    - name: 'Build ghdl/build:doc'
      if: (matrix.distro == 'debian') && (matrix.version == 'bullseye')
      run: |
        docker build -t ghdl/build:doc . -f- <<-EOF
        FROM ghdl/build:bullseye-mcode
        RUN apt update -qq && apt install -y python3-pip graphviz
        EOF

    - name: Login to DockerHub
      if: github.event_name != 'pull_request' && github.repository == 'ghdl/docker'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Deploy to DockerHub
      if: github.event_name != 'pull_request' && github.repository == 'ghdl/docker'
      run: ./run.sh base

# FIXIT: ensure that branches different from 'master' do not trigger deploy steps!
# FIXIT: ensure that PR's cannot access/use secrets!
