name: 'bullseye'

on:
  push:
    paths:
      - 'run.sh'
      - '.github/workflows/bullseye.yml'
  workflow_dispatch:
  repository_dispatch:
    types: [ ghdl ]

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        backend:
          - mcode
          - llvm-9
          - gcc-9.1.0
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Clone ghdl
      run: git clone https://github.com/ghdl/ghdl

    - name: Build 'ghdl' and 'pkg' images
      run: ./run.sh -b
      env:
        TASK: bullseye+${{ matrix.backend }}

    - name: 'Build ghdl/debug'
      if: matrix.backend == 'mcode'
      run: |
        docker build -t ghdl/debug - <<-EOF
        FROM ghdl/debug:base
        COPY --from=ghdl/pkg:bullseye-mcode / /ghdl/usr/local/
        EOF

    - name: Deploy to DockerHub
      if: github.event_name != 'pull_request' && github.repository == 'ghdl/docker'
      uses: pyTooling/Actions/with-post-step@r0
      with:
        main: |
          # Release
          echo '${{ secrets.DOCKER_PASS }}' | docker login docker.io -u '${{ secrets.DOCKER_USER }}' --password-stdin
          ./run.sh ""
        post: docker logout docker.io

  trigger:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: GHDL_BOT_TOKEN=${{ secrets.GHDL_BOT }} ./.github/trigger.sh vunit
