name: 'ext'

on:
  push:
    paths:
      - 'run.sh'
      - 'cli/*'
      - '.github/workflows/ext.yml'
      - 'ls_debian*.dockerfile'
      - 'gui.dockerfile'
  workflow_dispatch:
  repository_dispatch:
    types: [ ext ]

env:
  DOCKER_BUILDKIT: 1

jobs:


  ls:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build images
      run: ./run.sh -l

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Deploy to DockerHub
      run: ./run.sh ext


  gui:
    needs: [ls]
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build images
      run: ./run.sh -e gui

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Deploy to DockerHub
      run: ./run.sh ext
