name: 'test'

on:
  push:
    paths:
      - 'run.sh'
      - '.github/workflows/test.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        include: [
          { distro: buster,   backend: mcode ,     args: "" },
          { distro: buster,   backend: mcode,      args: "--gplcompat" },
          { distro: bullseye, backend: mcode,      args: "--gplcompat" },
          { distro: ubuntu20, backend: mcode ,     args: "" },
          { distro: ubuntu22, backend: mcode ,     args: "" },
          { distro: fedora35, backend: mcode ,     args: "" },
          { distro: fedora36, backend: mcode ,     args: "" },
          { distro: buster,   backend: llvm-7,     args: "" },
          { distro: ubuntu20, backend: llvm-10,    args: "" },
          { distro: ubuntu22, backend: llvm-11,    args: "" },
          { distro: fedora35, backend: llvm,       args: "" },
          { distro: fedora36, backend: llvm,       args: "" },
          { distro: buster,   backend: gcc-9.4.0,  args: "" },
          { distro: fedora35, backend: gcc-10.3.0, args: "" },
          { distro: fedora36, backend: gcc-11.3.0, args: "" },
        ]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Clone ghdl
      run: git clone https://github.com/ghdl/ghdl

    - name: Build 'ghdl' and 'pkg' images
      run: ./run.sh -b $TARGS
      env:
        TASK: ${{ matrix.distro }}+${{ matrix.backend }}
        TARGS: ${{ matrix.args }}

    - name: Login to DockerHub
      if: github.event_name != 'pull_request' && github.repository == 'ghdl/docker'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Deploy to DockerHub
      if: github.event_name != 'pull_request' && github.repository == 'ghdl/docker'
      run: ./run.sh ""
