name: 'vunit'

on:
  push:
    paths:
      - 'run.sh'
      - 'cli/*'
      - '.github/workflows/vunit.yml'
      - 'vunit.dockerfile'
  workflow_dispatch:
  repository_dispatch:
    types: [ vunit ]

env:
  DOCKER_BUILDKIT: 1

jobs:

  vunit:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build images
      run: ./run.sh -e vunit

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Deploy to DockerHub
      run: ./run.sh vunit

    - run: ./.github/trigger.sh ext
      env:
        GHDL_BOT_TOKEN: ${{ secrets.GHDL_BOT }}
